version: '3.9'

services:
  database:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: on-failure
    env_file: .env
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

  grpc_service:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      DATABASE: "in-memory"
    depends_on:
      database:
        condition: service_started